name: 'GitHub Action for Firebase '
author: 'Surekha Verma'
description: 'Wraps the firebase-tools CLI to enable common commands.'
branding:
  icon: 'package'
  color: 'gray-dark'
runs:
  using: 'docker'
  image: 'Dockerfile_New'
