name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: docker build & push
    runs-on: ubuntu-latest
    steps:
      - name: checkout scm
        uses: actions/checkout@v2
      - name: docker/build-push
        uses: docker/build-push-action@v2
        with:
          username: surekha-verma
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: surekha-verma/firebase-action-java
          tags: latest
